"""initial changes

Revision ID: 009a43b2e267
Revises: 0c84a0e8df97
Create Date: 2023-03-25 11:30:23.613543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009a43b2e267'
down_revision = '0c84a0e8df97'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
