"""initial changes

Revision ID: 0642414d4a34
Revises: ba03d0e338b7
Create Date: 2023-03-19 22:32:19.542534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0642414d4a34'
down_revision = 'ba03d0e338b7'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
