"""initial changes

Revision ID: 06a03592b043
Revises: b18d373c78d5
Create Date: 2023-03-19 22:51:46.587519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a03592b043'
down_revision = 'b18d373c78d5'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
