"""initial changes

Revision ID: 0c84a0e8df97
Revises: 4f3cdf6d513d
Create Date: 2023-03-25 11:29:29.355124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c84a0e8df97'
down_revision = '4f3cdf6d513d'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
