"""initial changes

Revision ID: 0cb014da4e80
Revises: 06a03592b043
Create Date: 2023-03-19 22:51:48.792748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb014da4e80'
down_revision = '06a03592b043'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
