"""initial changes

Revision ID: 1d7a274d85ce
Revises: 51672aca79da
Create Date: 2023-03-25 11:34:16.852222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7a274d85ce'
down_revision = '51672aca79da'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
