"""initial changes

Revision ID: 23418c143cac
Revises: 7473bebcf0dd
Create Date: 2023-03-19 22:39:18.343422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23418c143cac'
down_revision = '7473bebcf0dd'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
