"""initial changes

Revision ID: 28b924e2c613
Revises: bc0c1f440cd0
Create Date: 2023-03-19 22:33:27.712560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b924e2c613'
down_revision = 'bc0c1f440cd0'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
