"""initial changes

Revision ID: 2e39aea3205b
Revises: bf516e1ca8bb
Create Date: 2023-03-25 11:23:48.807128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e39aea3205b'
down_revision = 'bf516e1ca8bb'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
