"""initial changes

Revision ID: 32fdd26d893b
Revises: 4727d2344160
Create Date: 2023-03-19 22:56:04.870715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fdd26d893b'
down_revision = '4727d2344160'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
