"""initial changes

Revision ID: 368234d96853
Revises: 55c5d0b870e4
Create Date: 2023-03-19 22:14:08.201739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368234d96853'
down_revision = '55c5d0b870e4'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
