"""initial changes

Revision ID: 3899abb2454b
Revises: 695450bd3642
Create Date: 2023-03-25 11:20:28.593586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3899abb2454b'
down_revision = '695450bd3642'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
