"""initial changes

Revision ID: 3d3d33a4d3ec
Revises: 32fdd26d893b
Create Date: 2023-03-19 22:59:22.285504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3d33a4d3ec'
down_revision = '32fdd26d893b'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
