"""initial changes

Revision ID: 3f46843fbb3f
Revises: 368234d96853
Create Date: 2023-03-19 22:14:28.458688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f46843fbb3f'
down_revision = '368234d96853'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
