"""initial changes

Revision ID: 44d2120c4490
Revises: 3d3d33a4d3ec
Create Date: 2023-03-25 11:17:30.874249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d2120c4490'
down_revision = '3d3d33a4d3ec'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
