"""initial changes

Revision ID: 4727d2344160
Revises: 0cb014da4e80
Create Date: 2023-03-19 22:56:02.559364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4727d2344160'
down_revision = '0cb014da4e80'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
