"""initial changes

Revision ID: 485ac5a78ec6
Revises: f1e1e0144c45
Create Date: 2023-03-19 22:40:57.548148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485ac5a78ec6'
down_revision = 'f1e1e0144c45'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
