"""initial changes

Revision ID: 4f3cdf6d513d
Revises: 68eab41299a8
Create Date: 2023-03-25 11:29:26.417803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3cdf6d513d'
down_revision = '68eab41299a8'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
