"""initial changes

Revision ID: 5140491e3aa6
Revises: 1d7a274d85ce
Create Date: 2023-03-25 11:34:19.956266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5140491e3aa6'
down_revision = '1d7a274d85ce'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
