"""initial changes

Revision ID: 51672aca79da
Revises: f4cdff54e0cb
Create Date: 2023-03-25 11:33:43.955226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51672aca79da'
down_revision = 'f4cdff54e0cb'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
