"""initial changes

Revision ID: 55c5d0b870e4
Revises: 71c2bc4d4e16
Create Date: 2023-03-19 22:13:51.351592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c5d0b870e4'
down_revision = '71c2bc4d4e16'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
