"""initial changes

Revision ID: 59f36058fcdb
Revises: b1d5eba2dae9
Create Date: 2023-03-19 22:36:35.493861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f36058fcdb'
down_revision = 'b1d5eba2dae9'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
