"""initial changes

Revision ID: 5bb06fb52266
Revises: 3f46843fbb3f
Create Date: 2023-03-19 22:30:28.385087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb06fb52266'
down_revision = '3f46843fbb3f'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
