"""initial changes

Revision ID: 5c65c7710ba3
Revises: 5140491e3aa6
Create Date: 2023-03-25 11:45:08.090480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c65c7710ba3'
down_revision = '5140491e3aa6'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
