"""initial changes

Revision ID: 68eab41299a8
Revises: 2e39aea3205b
Create Date: 2023-03-25 11:23:51.748426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68eab41299a8'
down_revision = '2e39aea3205b'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
