"""initial changes

Revision ID: 695450bd3642
Revises: ef11950f0cd3
Create Date: 2023-03-25 11:20:25.621634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695450bd3642'
down_revision = 'ef11950f0cd3'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
