"""initial changes

Revision ID: 6f7104ed3398
Revises: 59f36058fcdb
Create Date: 2023-03-19 22:36:53.199398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7104ed3398'
down_revision = '59f36058fcdb'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
