"""initial changes

Revision ID: 71c2bc4d4e16
Revises: ada8a3a4007e
Create Date: 2023-03-19 22:13:43.341463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c2bc4d4e16'
down_revision = 'ada8a3a4007e'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
