"""initial changes

Revision ID: 7473bebcf0dd
Revises: d47dfde22704
Create Date: 2023-03-19 22:38:53.801914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7473bebcf0dd'
down_revision = 'd47dfde22704'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
