"""initial changes

Revision ID: 8e1ff0dfb722
Revises: dbdc7306baf6
Create Date: 2023-03-19 22:03:31.496022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1ff0dfb722'
down_revision = 'dbdc7306baf6'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
