"""initial changes

Revision ID: 9583700ddf89
Revises: 6f7104ed3398
Create Date: 2023-03-19 22:37:09.962419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9583700ddf89'
down_revision = '6f7104ed3398'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
