"""initial changes

Revision ID: 99cb1b4335ab
Revises: 9583700ddf89
Create Date: 2023-03-19 22:37:18.279064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cb1b4335ab'
down_revision = '9583700ddf89'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
