"""initial changes

Revision ID: 9d551c2858f2
Revises: daa74e6e8905
Create Date: 2023-03-25 11:45:41.671014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d551c2858f2'
down_revision = 'daa74e6e8905'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
