"""initial changes

Revision ID: acc9090120b6
Revises: 8e1ff0dfb722
Create Date: 2023-03-19 22:10:53.342502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc9090120b6'
down_revision = '8e1ff0dfb722'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
