"""initial changes

Revision ID: ada8a3a4007e
Revises: acc9090120b6
Create Date: 2023-03-19 22:13:31.196893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada8a3a4007e'
down_revision = 'acc9090120b6'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
