"""initial changes

Revision ID: b18d373c78d5
Revises: c08073a6db31
Create Date: 2023-03-19 22:44:27.418200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18d373c78d5'
down_revision = 'c08073a6db31'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
