"""initial changes

Revision ID: b1d5eba2dae9
Revises: e25da1a3e57b
Create Date: 2023-03-19 22:35:30.985711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d5eba2dae9'
down_revision = 'e25da1a3e57b'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
