"""initial changes

Revision ID: ba03d0e338b7
Revises: 5bb06fb52266
Create Date: 2023-03-19 22:32:17.121364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba03d0e338b7'
down_revision = '5bb06fb52266'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
