"""initial changes

Revision ID: bc0c1f440cd0
Revises: 0642414d4a34
Create Date: 2023-03-19 22:33:25.324378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0c1f440cd0'
down_revision = '0642414d4a34'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
