"""initial changes

Revision ID: bf516e1ca8bb
Revises: b4c883336833
Create Date: 2023-03-25 11:22:45.499262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf516e1ca8bb'
down_revision = 'b4c883336833'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
