"""initial changes

Revision ID: c08073a6db31
Revises: 485ac5a78ec6
Create Date: 2023-03-19 22:44:25.115801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08073a6db31'
down_revision = '485ac5a78ec6'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
