"""initial changes

Revision ID: c3bf7fb75420
Revises: 44d2120c4490
Create Date: 2023-03-25 11:17:34.030850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bf7fb75420'
down_revision = '44d2120c4490'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
