"""initial changes

Revision ID: ca01b74e3fcf
Revises: 23418c143cac
Create Date: 2023-03-19 22:39:54.174444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca01b74e3fcf'
down_revision = '23418c143cac'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
