"""initial changes

Revision ID: d47dfde22704
Revises: 99cb1b4335ab
Create Date: 2023-03-19 22:38:51.366319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47dfde22704'
down_revision = '99cb1b4335ab'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
