"""initial changes

Revision ID: daa74e6e8905
Revises: 5c65c7710ba3
Create Date: 2023-03-25 11:45:11.382587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa74e6e8905'
down_revision = '5c65c7710ba3'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
