"""initial changes

Revision ID: e25da1a3e57b
Revises: 28b924e2c613
Create Date: 2023-03-19 22:35:01.329388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25da1a3e57b'
down_revision = '28b924e2c613'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
