"""initial changes

Revision ID: ef11950f0cd3
Revises: c3bf7fb75420
Create Date: 2023-03-25 11:19:04.795453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef11950f0cd3'
down_revision = 'c3bf7fb75420'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
