"""initial changes

Revision ID: f1e1e0144c45
Revises: ca01b74e3fcf
Create Date: 2023-03-19 22:40:01.536679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e1e0144c45'
down_revision = 'ca01b74e3fcf'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
