"""initial changes

Revision ID: f4cdff54e0cb
Revises: f67be578e74a
Create Date: 2023-03-25 11:33:39.795349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cdff54e0cb'
down_revision = 'f67be578e74a'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
