"""initial changes

Revision ID: f67be578e74a
Revises: 009a43b2e267
Create Date: 2023-03-25 11:30:26.898548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67be578e74a'
down_revision = '009a43b2e267'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
