"""initial changes

Revision ID: fb9d813416ca
Revises: 9d551c2858f2
Create Date: 2023-03-25 11:45:44.821305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9d813416ca'
down_revision = '9d551c2858f2'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
